CREATE TABLE [dbo].[Movie]
(
	[Id_Movie] INT NOT NULL PRIMARY KEY IDENTITY,
	[Title] NVARCHAR(64) NOT NULL,
	[SubTitle] NVARCHAR(64) NULL,
	[ReleaseYears] SMALLINT NOT NULL,
	[Synopsis] NVARCHAR(256) NOT NULL,
	[PosterUrl] NVARCHAR(256) NOT NULL,
	[Duration] INT NOT NULL,

)
